Repository vknet/vk, pull requests merged in 2018-10, with the labels that each got.

#688 BotsLongPoll изменения типа Ts с ulong на string
  VkNet.Tests/Categories/BotsLongPoll/BotsLongPollBoardTest.cs
  VkNet.Tests/Categories/BotsLongPoll/BotsLongPollFailed.cs
  VkNet.Tests/Categories/BotsLongPoll/BotsLongPollGroupTest.cs
  VkNet.Tests/Categories/BotsLongPoll/BotsLongPollMarketTest.cs
  VkNet.Tests/Categories/BotsLongPoll/BotsLongPollMessageTest.cs
  VkNet.Tests/Categories/BotsLongPoll/BotsLongPollPhotoTest.cs
  VkNet.Tests/Categories/BotsLongPoll/BotsLongPollVideoTest.cs
  VkNet.Tests/Categories/BotsLongPoll/BotsLongPollWallTest.cs
  VkNet/Exception/LongPollOutdateException.cs
  VkNet/Model/BotsLongPollHistoryResponse.cs
  VkNet/Model/RequestParams/Groups/BotsLongPollHistoryParams.cs
Labels: Pull Request

#690 Реализован WriteJson у AttachmentJsonConverter
  VkNet.Tests/Utils/JsonConverter/AttachmentJsonConverterTests.cs
  VkNet/Utils/JsonConverter/AttachmentJsonConverter.cs
Labels: Pull Request

#696 Обновлён message.getHistory
  VkNet.Tests/Categories/Messages/MessageGetHistoryTest.cs
  VkNet.Tests/Categories/Messages/MessagesCategoryTest.cs
  VkNet.Tests/Categories/Messages/MessagesGetObjectTests.cs
  VkNet/Abstractions/Category/Async/IMessagesCategoryAsync.cs
  VkNet/Abstractions/Category/IMessagesCategory.cs
  VkNet/Categories/Async/MessagesCategoryAsync.cs
  VkNet/Categories/MessagesCategory.cs
  VkNet/Model/MessageGetHistoryObject.cs
  VkNet/Model/RequestParams/Messages/MessagesGetHistoryParams.cs
Labels: Pull Request, Задача

#698 исправил зависание таска в TryInvokeMethodAsync
  VkNet/Utils/TypeHelper.cs
Labels: Pull Request, Ошибка

#706 Добавил конвертер и десериализацию пустого Activity, которая приходит из ВК в виде пустого массива
  VkNet.Tests/Categories/StatsTest.cs
  VkNet/Model/Activity.cs
  VkNet/Utils/JsonConverter/IgnoreUnexpectedArraysConverter.cs
Labels: Pull Request
