Repository vknet/vk, pull requests merged in 2019-01, with the labels that each got.

#774 Update styles to fix thin fonts on macOS
  stylesheets/styles.css
Labels: Pull Request

#776 Add RandomId in message.send
  categories/messages/send.md
Labels: Документация

#780 Исправил возможность построить пустую клавиатуру, удалить установленную клавиатуру в чате
  VkNet/Model/Keyboard/IKeyboardBuilder.cs
  VkNet/Model/Keyboard/KeyboardBuilder.cs
Labels: Pull Request

#784 Использовать один инстанс HttpClient для запросов
  VkNet/Utils/RestClient.cs
Labels: Задача

#785 Реализовать IDisposable для RestClient
  VkNet/Abstractions/Utils/IRestClient.cs
  VkNet/Utils/RestClient.cs
  VkNet/VkApi.cs
Labels: Задача
