Repository vknet/vk, pull requests merged in 2020-07, with the labels that each got.

#1021 Фикс KeyboardBuilder.Clear
  VkNet/Model/Keyboard/KeyboardBuilder.cs
Labels: Pull Request

#1026 Добавить параметр conversation_message_id в message.edit
  VkNet/Categories/MessagesCategory.cs
  VkNet/Model/RequestParams/Messages/MessageEditParams.cs
Labels: Задача

#1025 Добавить callback-кнопки и метод SendMessageEventAnswer
  VkNet.Tests/Categories/BotsLongPoll/BotsLongPollMessageTest.cs
  VkNet.Tests/Categories/Messages/MessagesSendMessageEventAnswerTests.cs
  VkNet.Tests/TestData/Categories/BotsLongPoll/GetBotsLongPollHistory_MessageEventTest.json
  VkNet/Abstractions/Category/Async/IMessagesCategoryAsync.cs
  VkNet/Abstractions/Category/IMessagesCategory.cs
  VkNet/Categories/Async/MessagesCategoryAsync.cs
  VkNet/Categories/MessagesCategory.cs
  VkNet/Enums/SafetyEnums/GroupUpdateType.cs
  VkNet/Enums/SafetyEnums/KeyboardButtonActionType.cs
  VkNet/Enums/SafetyEnums/MessageEventType.cs
  VkNet/Model/EventData.cs
  VkNet/Model/GroupUpdate/GroupUpdate.cs
  VkNet/Model/GroupUpdate/MessageEvent.cs
  VkNet/Model/Keyboard/IKeyboardBuilder.cs
  VkNet/Model/Keyboard/KeyboardBuilder.cs
  VkNet/Utils/VkResponseToSafetyEnumCastGenerator.cs
Labels: Задача

#1027 Исправлена опечатка, добавлена перегрузка метода добавления кнопки и написаны тесты для SafetyEnums
  VkNet.Tests/Enum/SafetyEnums/SafetyEnumTests.cs
  VkNet/Enums/SafetyEnums/MessageEventType.cs
  VkNet/Model/Keyboard/IKeyboardBuilder.cs
  VkNet/Model/Keyboard/KeyboardBuilder.cs
Labels: Задача

#1028 #999 messages.send: reply_to, subscribe_id
  VkNet/Categories/MessagesCategory.cs
  VkNet/Model/RequestParams/Messages/MessagesSendParams.cs
Labels: Pull Request, Задача

#1036 Обновить категорию Account
  VkNet.Tests/Categories/Account/AccountCategoryTest.cs
  VkNet/Abstractions/Category/Async/IAccountCategoryAsync.cs
  VkNet/Abstractions/Category/IAccountCategory.cs
  VkNet/Categories/AccountCategory.cs
  VkNet/Categories/Async/AccountCategoryAsync.cs
  VkNet/Enums/Filters/CountersFilter.cs
Labels: Category, Pull Request

#1035 Добавить параметры template и keyboard в MessageEditParams
  VkNet/Categories/MessagesCategory.cs
  VkNet/Model/RequestParams/Messages/MessageEditParams.cs
Labels: Pull Request

#1038 #1012 Добавить метод wall.checkCopyrightLink
  VkNet.Tests/Categories/Wall/WallCategoryTest.cs
  VkNet/Abstractions/Category/Async/IWallCategoryAsync.cs
  VkNet/Abstractions/Category/IWallCategory.cs
  VkNet/Categories/Async/WallCategoryAsync.cs
  VkNet/Categories/WallCategory.cs
Labels: Pull Request

#1041 Установить версию апи 5.120 по умолчанию
  VkNet/Infrastructure/VkApiVersionManager.cs
Labels: Pull Request

#1040 #959 Скрыть токен и пароли при выводе JSON в логи
  VkNet/Utils/Utilities.cs
Labels: Pull Request

#1043 Добавить метод streaming.getStem
  VkNet.Tests/Categories/Streaming/StreamingCategoryTests.cs
  VkNet.Tests/TestData/Categories/Streaming/GetStem.json
  VkNet/Abstractions/Category/Async/IStreamingCategoryAsync.cs
  VkNet/Abstractions/Category/IStreamingCategory.cs
  VkNet/Categories/Async/StreamingCategoryAsync.cs
  VkNet/Categories/StreamingCategory.cs
Labels: Pull Request

#1048 #1047 Исправить null reference при получении подкастов (поле Position)
  VkNet/Model/PodcastInfo.cs
Labels: Pull Request
