Repository vknet/vk, pull requests merged in 2021-02, with the labels that each got.

#1138 Fix #1137
  VkNet/Model/RequestParams/Messages/MessagesSendParams.cs
Labels: Pull Request

#1140 Исправлен баг с неправильной обработкой капчи при авторизации #1139
  VkNet.Tests/Infrastructure/AuthorizationFormHtmlParserTests.cs
  VkNet/Infrastructure/Authorization/ImplicitFlow/AuthorizationFormHtmlParser.cs
  VkNet/Infrastructure/Authorization/ImplicitFlow/Forms/ImplicitFlowCaptchaLoginForm.cs
  VkNet/Infrastructure/Authorization/ImplicitFlow/VkHtmlFormResult.cs
Labels: Ошибка

#1141 В метод MarkAsRead и MarkAsReadAsync добавлен параметр markConservationAsRead #1129
  VkNet/Abstractions/Category/Async/IMessagesCategoryAsync.cs
  VkNet/Abstractions/Category/IMessagesCategory.cs
  VkNet/Categories/Async/MessagesCategoryAsync.cs
  VkNet/Categories/MessagesCategory.cs
Labels: Задача

#1143 Исправлен баг с крашем при использовании NewsFeed.Search() #1049
  VkNet.Tests/Categories/NewsFeed/SearchTests.cs
  VkNet.Tests/TestData/Categories/NewsFeed/Search_PostSourceData_Parsing.json
  VkNet/Model/Attachments/Link.cs
  VkNet/Model/PostSource.cs
  VkNet/Model/PostSourceData.cs
Labels: Ошибка
