Repository vknet/vk, pull requests merged in 2021-09, with the labels that each got.

#1195 Исправлен баг в методе ImplicitFlowVkAuthorization.GetPageType(Uri uri) #1169
  VkNet.Tests/Infrastructure/BaseTest.cs
  VkNet.Tests/Infrastructure/ImplicitFlowVkAuthorizationTests.cs
  VkNet/Infrastructure/Authorization/ImplicitFlow/ImplicitFlowVkAuthorization.cs
Labels: Pull Request

#1196 Исправлен тип данных у свойства OwnerId - id сообщества
  VkNet/Model/EventData.cs
  VkNet/Model/Keyboard/MessageKeyboardButtonAction.cs
Labels: Pull Request

#1201 Реализация IsValid в ApiAuthParams
  VkNet.Tests/Categories/Auth/ApiAuthParamsTests.cs
  VkNet.Tests/Models/SettingsTests.cs
  VkNet/Enums/Filters/Settings.cs
  VkNet/Model/RequestParams/Auth/ApiAuthParams.cs
  VkNet/Model/RequestParams/Auth/IApiAuthParams.cs
Labels: Pull Request

#1200 Фикс времени AwaitableConstraint и его теста.
  VkNet.Tests/Utils/CountByIntervalAwaitableConstraintTests.cs
  VkNet.Tests/VkApiTest.cs
  VkNet/Utils/CountByIntervalAwaitableConstraint.cs
Labels: Ошибка

#1205 Ограничения методов Ads.CreateCampaign и Ads.CreateClients
  VkNet/Categories/AdsCategory.cs
  VkNet/Model/Results/Ads/CreateCampaignResult.cs
  VkNet/Model/Results/Ads/CreateClientResult.cs
Labels: Pull Request

#1203 Исправление поведения MessagesCategory.SetActivity
  VkNet.Tests/Categories/Messages/MessagesCategoryTest.cs
  VkNet.Tests/Categories/Messages/MessagesSetActivityTests.cs
  VkNet/Categories/MessagesCategory.cs
Labels: Pull Request

#1199 Замена русских букв в названиях полей.
  VkNet/Abstractions/Category/Async/IDocsCategoryAsync.cs
  VkNet/Abstractions/Category/Async/IFriendsCategoryAsync.cs
  VkNet/Abstractions/Category/Async/IGroupsCategoryAsync.cs
  VkNet/Abstractions/Category/Async/ILikesCategoryAsync.cs
  VkNet/Abstractions/Category/Async/IPhotoCategoryAsync.cs
  VkNet/Abstractions/Category/IMessagesCategory.cs
  VkNet/Categories/Async/MessagesCategoryAsync.cs
  VkNet/Categories/MessagesCategory.cs
  VkNet/Enums/Filters/Settings.cs
  VkNet/Exception/OnlyStandaloneOrOpenApiException.cs
  VkNet/Exception/TooManyAdsPostsException.cs
  VkNet/Model/Ads/AdsAccount.cs
  VkNet/Model/Ads/AdsCampaign.cs
  VkNet/Model/Audio/AudioCatalogAudioAds.cs
  VkNet/Model/Currency.cs
  VkNet/Model/Topic.cs
  VkNet/Obsolete/Utils/Async/Browser.Async.cs
  VkNet/Obsolete/Utils/Browser.cs
  VkNet/Utils/ObsoleteText.cs
  VkNet/Utils/PerformanceActivator.cs
  VkNet/Utils/TypeHelper.cs
  VkNet/Utils/VkErrorCode.cs
Labels: Ошибка, Pull Request

#1207 Добавление поля "video" в вложение "Звонок"
  VkNet.Tests/Categories/Messages/MessagesWithCallTests.cs
  VkNet.Tests/TestData/Models/message_with_call.json
  VkNet/Model/Attachments/Call.cs
Labels: Pull Request

#1208 Огромное расширение модели видео
  VkNet/Enums/SafetyEnums/VideoAdsSection.cs
  VkNet/Model/Attachments/Video.cs
  VkNet/Model/Video/LiveSettings.cs
  VkNet/Model/Video/TimelineThumbs.cs
  VkNet/Model/Video/VideoAds.cs
  VkNet/Model/Video/VideoAdsParams.cs
  VkNet/Model/VideoFiles.cs
Labels: Pull Request

#1209 Добавление тестов для новых полей Video после #1208
  VkNet.Tests/Models/VideoModel.cs
  VkNet.Tests/TestData/Models/video_live.json
  VkNet.Tests/TestData/Models/video_with_ads_and_timeline.json
  VkNet/Model/Attachments/Video.cs
  VkNet/Model/Video/LiveSettings.cs
  VkNet/Model/Video/TimelineThumbs.cs
  VkNet/Model/Video/VideoAds.cs
  VkNet/Model/Video/VideoAdsParams.cs
Labels: Pull Request
